name: typetreeflow
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - biopython
  - pandas
  - seaborn
  - pytest
  - ncbi-datasets-cli
  - barrnap
  - bedtools
  - fastani
  - mafft
  - trimal
  - iqtree
  - pip
  - pip:
      - lpsn>=1.0.0
